### PR TITLE
Add support for recursive `oneof` fields

### PR DESCRIPTION
**Pull request by olix0r**
Currently, `oneof`s that reference a parent type result in compile errors.

By replicating the `boxed` check in field generation, oneofs may be recursive.

Fixes danburkert/prost#46

### CODE REVIEW

**Comment by danburkert** [comment]
Good catch, thanks for the PR.  The CI failure is because the bootstrap test is failing - it's picking up nesting even through a map field.  You can reproduce with `cargo test --all`.  I think this is a bug even with the original message nesting; we're checking that it's not repeated, but we're not checking that it's not a map field.  Could you add your test case to `tests`, and extend it with repeated and map fields to make sure those don't box?

**Comment by danburkert** [comment]
>  I think this is a bug even with the original message nesting; we're checking that it's not repeated, but we're not checking that it's not a map field.

**Comment by olix0r** [comment]
@danburkert Thanks. I've pushed a change with a test case.

Unfortunately, when we check to see whether a oneof variant references an outer type, we don't know whether this reference is through a list or map. This causes the sometimes-unncessary boxing of oneof variants so that the size of a oneof is always known at compile-time.

Updating prost-types to have admit these unnecessary boxes allows the bootstrap test to pass.

I understand that this boxing is undesirable, but I don't understand this code base well enough to propose a solution that does not incur this cost. I'm open to other ideas.

**Comment by danburkert** [comment]
I think I found a relatively simple workaround for the boxing issue.  We'll see what CI says :).

**Comment by danburkert** [comment]
Squashed to master manually.  Thanks again for the PR.  Would a point release be helpful for y'all?

**Comment by danburkert** [comment]
Fixed in 0.2.3.

**Pull request closed without merging**
