### PR TITLE
Update bytes 0.5

### PR DESCRIPTION
**Pull request by danburkert**
This is #246, rebased over current master and with a commit containing some additional fixups.  I didn't want to clobber @LucioFranco's branch so it's in a separate PR.

### CODE REVIEW

**Comment by danburkert** [comment]
@LucioFranco apologies, I merged this via 'squash', which I did not realize would overwrite the git author metadata. I've corrected that mistake on master by forcibly rewriting the commits.

**Comment by LucioFranco** [comment]
@danburkert thank you! <3 Do you know when we could expect a release with this bytes change? I am hoping to ship tonic this weekend but currently, I am doing a couple of workarounds to use the current version. The biggest issue is having to have users include `bytes = 0.4` which may be confusing but I am happy to hold off or also just release with that.

**Comment by danburkert** [comment]
I'm planning to release soon, but I'm currently traveling so I can't commit to the end of the week (It's already Saturday where I am!).  I'm planning for sometime next week, but there are still a few PR's I want to get landed, including the quote/syn bump which is a bit hairy.

**Comment by LucioFranco** [comment]
Ok that is fine, I think what I'll do then is release (maybe this weekend) `tonic 0.1` with bytes 0.4 hack for prost. Then once you are ready to release I can bump to 0.2. So that there is no rush for you and you can make sure things are good.

**Comment by danburkert** [comment]
Sounds good, thanks!

**Comment by LucioFranco** [comment]
also I want to note that if there is something I can help with here please let me know! I am gonna hold off a bit on the relase, since there are some other parts that need work but I am also happy to help out here to move things a long.

**Comment by Hoverbear** [comment]
@danburkert I happen to know you have many eager beavers hoping for that new release. :) Any chance you can put some time aside?

**Pull request merged**
