### PR TITLE
add generics support for derives

### LINKED ISSUE #280: prost-derive generic type?
Hi there!

Currently prost-derive does not handle generics. I have a use case where I would need to have something like this:

```rust
pub trait MyTrait: prost::Message + other stuff...

#[derive(prost::Message, ....)]
struct Element<A: MyTrait> {
   #[prost(message, tag = "1")]
   data: A,
   #[prost(uint64, tag = "2")]
   timestamp:  u64,
}
```
As long as the generic implements prost::Message, it shouldn't be any problem I guess?  Just thought I would post here first to see if it is an easy change before I start working on a PR for it.

Cheers

### PR DESCRIPTION
**Pull request by Max-Meldrum**
Perhaps other people are interested in a similar use case as mine, so here is a PR for adding generics support for prost-derive.

Closes #280

### CODE REVIEW

**Comment by sphw** [comment]
Just bumping this PR. @danburkert I am wondering if there is any extra work that needs to be done to get it merged? I would find this feature very useful

**Comment by Max-Meldrum** [comment]
Fixed the latest merge conflicts  @danburkert 

I understand it is not a prioritisation, but it is a small change and a non-breaking one. Please let me know if there is anything I can do to improve it :)

**Comment by Max-Meldrum** [comment]
Giving this another bump @danburkert 

All tests pass except rustfmt, not sure what is happening there.

**Review by danburkert — APPROVED** [review]
Nice looks good, sorry for being slow to review!

**Pull request merged**
