### PR TITLE
Update bytes to 0.6

### PR DESCRIPTION
**Pull request by olix0r**
This change updates the `bytes` crate dependencies to version 0.6.

Fixes https://github.com/danburkert/prost/issues/380

### CODE REVIEW

**Comment by olix0r** [comment]
I don't have much context on the prior implementations to be confident that the ported version is absolutely correct, but at least the tests all pass locally.

**Comment by olix0r** [comment]
This CI failure appears to be unrelated to my change?
```
error[E0658]: the `#[non_exhaustive]` attribute is an experimental feature
224
Error:    --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/curl-0.4.34/src/easy/handler.rs:395:1
225
    |
226
395 | #[non_exhaustive]
227
    | ^^^^^^^^^^^^^^^^^
228
    |
229
    = note: for more information, see https://github.com/rust-lang/rust/issues/44109
230
```

**Comment by wchargin** [comment]
CI failure is indeed unrelated; #382 should fix.

**Comment by danburkert** [comment]
Took a look, this unfortunately results in a very significant perf hit during encoding.  I switched `encode_varint` back to something closer to the `master` version:

```rust
    unsafe {
        let mut i;
        'outer: loop {
            i = 0;

            let uninit_slice = buf.bytes_mut();
            let ptr = uninit_slice.as_mut_ptr();
            for offset in 0..uninit_slice.len() {
                i += 1;
                let ptr = ptr.offset(offset as isize);
                if value < 0x80 {
                    ptr.write(value as u8);
                    break 'outer;
                } else {
                    ptr.write(((value & 0x7F) | 0x80) as u8);
                    value >>= 7;
                }
            }

            buf.advance_mut(i);
            debug_assert!(buf.has_remaining_mut());
        }

        buf.advance_mut(i);
    }
```

but that still is ~40-50% slower in the in-tree benchmarks (both the synthetic `varint` and the more real world protobuf benchmarks).  Will keep looking into this as I have time, #279 may be a good way to sidestep the issue.  My early thoughts are that this is related to slowness in the new `UninitSlice` API, perhaps there is an `#[inline]` tag missing, or it just doesn't optimize as well.

**Comment by danburkert** [comment]
It was indeed missing `#[inline]` tags in `bytes`.  Closing in favor of #387.  Thanks @olix0r !

**Pull request closed without merging**
