### PR TITLE
Don't write prost-build output if its content is unchanged

### LINKED ISSUE #139: prost-build triggers rebuild on arbitrary file change
Let's say I have some rust project and have done `cargo build`. Now I touch an arbitrary file around there, eg `touch x`. If I run `cargo build` now, it is very fast and mostly figures out it doesn't need to do anything.

However, this changes if I introduce `prost-build` into the project. Now the `cargo build` will rebuild the whole crate (and all the tests and other things if it is not `cargo build` but eg. `cargo test --all`).

My guess is, this has something to do with the fact that the file change provokes `build.rs` to be re-run. That one, in turn, overwrites the `rs` files generated from protobufs, which triggers the rebuild (even though the produced files are the same).

If my guess is correct, would it make sense to generate them to some temporary file first (eg. `generated_file.rs.tmp`), compare with the previous version (if present) and then move it into place only if it differs?

### LINKED ISSUE #231: Only write files when the contents have changed
As a workaround to code completion not working (#229), and because I've decided it is a good idea anyway, I changed my `build.rs` to output the generated code to the source directory.

Unfortunately it completely breaks rust-analyzer which watches the code for changes, then runs `build.rs` and gets stuck in a loop.

Probably should be fixed there, but I think a simple and worthwhile fix would be for prost-build to only write files if their contents have changed. I've used this technique in a CMake based project and it works very well.

Might fix #139 too, who knows.

### PR DESCRIPTION
**Pull request by Timmmm**
This means things like cargo-watch work better. Fixes #231

### CODE REVIEW

**Comment by Timmmm** [comment]
This is also necessary if you are using [`cross`](https://github.com/rust-embedded/cross) because it makes the source directory read-only.

I think the CI failure is unrelated.

**Comment by dbrgn** [comment]
Couldn't this solved with this in `build.rs`?

```rust
println!("cargo:rerun-if-changed=path/to/schema.proto");
```

**Comment by Timmmm** [comment]
No. That just means that cargo will re-trigger a build if `schema.proto` changes, which it already does by default as long as `schema.proto` is inside your crate directory.

If anything you would want something like:

    println!("cargo:DONT-rerun-if-changed=path/to/output.rs");

But that is way more ugly and less robust than this change.

**Comment by dbrgn** [comment]
> No. That just means that cargo will re-trigger a build if schema.proto changes, which it already does by default as long as schema.proto is inside your crate directory.

Ah, I assume that didn't work for me because my proto files are in a submodule adjacent to the `src` directory, not inside.

**Comment by Timmmm** [comment]
> Ah, I assume that didn't work for me because my proto files are in a submodule adjacent to the `src` directory, not inside.

Yeah I'm not sure actually what the default behaviour is meant to be - the documentation is not clear:

> Normally build scripts are re-run if any file inside the crate root changes, but this can be used to scope changes to just a small set of files.

Is "the crate root" the directory containing `Cargo.toml`, or is it `src`, and does it check recursively?

In any case, this patch is a much better approach.

**Comment by Timmmm** [comment]
However there may be a separate bug in that it should *also* be printing `println!("cargo:rerun-if-changed=path/to/schema.proto");` for all of the input files. That could be left up to the user I guess but if so it should probably be added to the documentation for this crate because it's a pretty obscure thing to know about!

**Comment by Timmmm** [comment]
Is there anything left to do before landing this?

**Comment by danburkert** [comment]
> However there may be a separate bug in that it should _also_ be printing `println!("cargo:rerun-if-changed=path/to/schema.proto");` for all of the input files. That could be left up to the user I guess but if so it should probably be added to the documentation for this crate because it's a pretty obscure thing to know about!

This is 'discussed' [in the source](https://github.com/danburkert/prost/blob/master/prost-build/src/lib.rs#L504-L508), but it's not enabled since it isn't the right thing to do for a build.rs which is also handling other responsibilities, e.g. compiling a native C dylib and doing `prost` codegen.  I think I'd be in support of an additional codegen flag which caused these lines to be emitted, and I'd almost go so far as to say it should be on by default.

**Comment by danburkert** [comment]
Merged to master with minor changes in #8c647.  Thanks for the PR, @Timmmm!  If anyone wants to continue the discussion of `rerun-if-changed`, I invite you to open an issue to discuss.

**Comment by shahn** [comment]
`rerun-if-changed`  is already discussed in #139

**Pull request closed without merging**
